import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  RefreshCw, 
  Download, 
  ZoomIn, 
  ZoomOut, 
  Maximize2, 
  X, 
  ChevronDown, 
  ChevronUp, 
  Sparkles, 
  GitBranch,
  AlertTriangle
} from 'lucide-react';

/**
 * AI-Generated Concept Image Renderer
 * Displays educational images generated by Gemini 2.5 Flash (Nano Banana)
 * Falls back to mermaid block diagram if image generation fails
 */
export default function VisualizationRenderer({ 
  visualizationData,
  topic,
  onRegenerate
}) {
  const [expanded, setExpanded] = useState(true);
  const [zoom, setZoom] = useState(1);
  const [fullscreen, setFullscreen] = useState(false);
  const [showDescription, setShowDescription] = useState(false);

  if (!visualizationData) return null;

  const isImage = visualizationData.type === 'generated_image' && visualizationData.image;
  const isMermaid = visualizationData.type === 'mermaid' || visualizationData.mermaid;
  const isFallback = visualizationData.fallback === true;

  // Build image src from base64
  const imageSrc = isImage 
    ? `data:${visualizationData.mime_type || 'image/png'};base64,${visualizationData.image}` 
    : null;

  // Download the image
  const handleDownload = () => {
    if (!imageSrc) return;
    const link = document.createElement('a');
    link.href = imageSrc;
    link.download = `${(topic || 'concept').replace(/\s+/g, '_')}_visualization.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Zoom controls
  const zoomIn = () => setZoom(z => Math.min(z + 0.25, 3));
  const zoomOut = () => setZoom(z => Math.max(z - 0.25, 0.5));
  const resetZoom = () => setZoom(1);

  // ==========================================
  // Mermaid Fallback Renderer (block diagram)
  // ==========================================
  const MermaidFallback = () => {
    let mermaidCode = '';
    try {
      if (typeof visualizationData === 'string') mermaidCode = visualizationData;
      else if (visualizationData.mermaid) mermaidCode = visualizationData.mermaid;
      else mermaidCode = JSON.stringify(visualizationData, null, 2);
    } catch {
      mermaidCode = 'Unable to parse diagram';
    }

    // Simple parser for flowchart nodes
    const nodes = [];
    const nodePattern = /(\w+)\s*(?:\[([^\]]+)\]|\(\(([^)]+)\)\)|\{([^}]+)\}|\(([^)]+)\))/g;
    let match;
    while ((match = nodePattern.exec(mermaidCode)) !== null) {
      const id = match[1];
      const label = match[2] || match[3] || match[4] || match[5] || id;
      if (!['flowchart', 'graph', 'subgraph', 'end', 'TD', 'LR', 'TB'].includes(id)) {
        if (!nodes.find(n => n.id === id)) {
          nodes.push({ id, label: label.trim() });
        }
      }
    }

    return (
      <div className="space-y-4">
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 flex items-start gap-2">
          <AlertTriangle size={16} className="text-amber-500 mt-0.5 flex-shrink-0" />
          <p className="text-sm text-amber-700">
            AI image generation unavailable. Showing simplified concept map instead.
          </p>
        </div>
        
        <div className="bg-gradient-to-br from-slate-50 to-white rounded-xl border border-slate-200 p-6">
          <div className="flex flex-wrap gap-3 justify-center">
            {nodes.map((node, i) => (
              <motion.div
                key={node.id}
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: i * 0.08 }}
                className="relative"
              >
                <div className={`px-4 py-2.5 rounded-lg border-2 text-sm font-medium shadow-sm ${
                  i === 0 ? 'bg-green-500 text-white border-green-400' :
                  i === nodes.length - 1 ? 'bg-blue-500 text-white border-blue-400' :
                  'bg-white text-gray-800 border-gray-200'
                }`}>
                  {node.label}
                </div>
                {i < nodes.length - 1 && (
                  <div className="absolute -right-4 top-1/2 -translate-y-1/2 text-gray-300 font-bold">→</div>
                )}
              </motion.div>
            ))}
          </div>
        </div>

        <details className="text-xs text-gray-500">
          <summary className="cursor-pointer hover:text-gray-700">View raw Mermaid code</summary>
          <pre className="mt-2 bg-gray-50 p-3 rounded-lg overflow-auto max-h-32 font-mono border">{mermaidCode}</pre>
        </details>
      </div>
    );
  };

  // ==========================================
  // Main Image Renderer
  // ==========================================
  return (
    <>
      {/* Fullscreen Modal */}
      <AnimatePresence>
        {fullscreen && imageSrc && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-black/90 flex items-center justify-center p-4"
            onClick={() => setFullscreen(false)}
          >
            <motion.div
              initial={{ scale: 0.9 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0.9 }}
              className="relative max-w-[95vw] max-h-[95vh]"
              onClick={e => e.stopPropagation()}
            >
              <button
                onClick={() => setFullscreen(false)}
                className="absolute -top-10 right-0 text-white/80 hover:text-white p-2 rounded-full hover:bg-white/10 transition-colors"
              >
                <X size={24} />
              </button>
              <img
                src={imageSrc}
                alt={`Concept visualization: ${topic}`}
                className="max-w-full max-h-[90vh] rounded-lg shadow-2xl object-contain"
              />
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Card */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white rounded-xl border border-gray-200 overflow-hidden shadow-sm"
      >
        {/* Header */}
        <div 
          className="flex items-center justify-between p-4 border-b border-gray-100 bg-gradient-to-r from-purple-50 to-white cursor-pointer"
          onClick={() => setExpanded(!expanded)}
        >
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-gradient-to-br from-purple-500 to-indigo-600 rounded-xl flex items-center justify-center shadow-lg">
              {isImage ? <Sparkles size={20} className="text-white" /> : <GitBranch size={20} className="text-white" />}
            </div>
            <div>
              <h4 className="font-semibold text-gray-900">
                {isImage ? 'AI-Generated Concept Image' : 'Process Flow Diagram'}
              </h4>
              <p className="text-xs text-gray-500">
                {topic} {isImage ? '• Powered by Gemini' : isFallback ? '• Fallback mode' : ''}
              </p>
            </div>
          </div>
          
          <div className="flex items-center space-x-1">
            {isImage && (
              <>
                <button
                  onClick={(e) => { e.stopPropagation(); zoomOut(); }}
                  className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
                  title="Zoom out"
                >
                  <ZoomOut size={16} />
                </button>
                <button
                  onClick={(e) => { e.stopPropagation(); resetZoom(); }}
                  className="px-2 py-1 text-xs text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors font-medium"
                  title="Reset zoom"
                >
                  {Math.round(zoom * 100)}%
                </button>
                <button
                  onClick={(e) => { e.stopPropagation(); zoomIn(); }}
                  className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
                  title="Zoom in"
                >
                  <ZoomIn size={16} />
                </button>
                <button
                  onClick={(e) => { e.stopPropagation(); setFullscreen(true); }}
                  className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
                  title="Full screen"
                >
                  <Maximize2 size={16} />
                </button>
                <button
                  onClick={(e) => { e.stopPropagation(); handleDownload(); }}
                  className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
                  title="Download image"
                >
                  <Download size={16} />
                </button>
              </>
            )}
            {onRegenerate && (
              <button
                onClick={(e) => { e.stopPropagation(); onRegenerate(); }}
                className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
                title="Regenerate"
              >
                <RefreshCw size={16} />
              </button>
            )}
            <button className="p-2 text-gray-400">
              {expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
            </button>
          </div>
        </div>

        {/* Content */}
        <AnimatePresence>
          {expanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.3 }}
              className="overflow-hidden"
            >
              <div className="p-6">
                {isImage ? (
                  /* ===== AI Generated Image ===== */
                  <div className="space-y-4">
                    {/* Image Container */}
                    <div 
                      className="relative overflow-auto rounded-xl border border-gray-100 bg-gradient-to-br from-slate-50 to-white"
                      style={{ maxHeight: '600px' }}
                    >
                      <div 
                        className="flex justify-center p-4 transition-transform duration-200"
                        style={{ transform: `scale(${zoom})`, transformOrigin: 'top center' }}
                      >
                        <img
                          src={imageSrc}
                          alt={`Educational concept visualization for ${topic}`}
                          className="max-w-full h-auto rounded-lg shadow-md"
                          style={{ maxHeight: zoom === 1 ? '500px' : 'none' }}
                        />
                      </div>
                    </div>

                    {/* Description (if model returned text alongside image) */}
                    {visualizationData.description && (
                      <div>
                        <button
                          onClick={() => setShowDescription(!showDescription)}
                          className="flex items-center gap-2 text-sm text-purple-600 hover:text-purple-800 font-medium transition-colors"
                        >
                          <Sparkles size={14} />
                          {showDescription ? 'Hide' : 'Show'} AI Description
                          {showDescription ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                        </button>
                        <AnimatePresence>
                          {showDescription && (
                            <motion.div
                              initial={{ height: 0, opacity: 0 }}
                              animate={{ height: 'auto', opacity: 1 }}
                              exit={{ height: 0, opacity: 0 }}
                              className="overflow-hidden"
                            >
                              <p className="mt-2 text-sm text-gray-600 bg-purple-50 rounded-lg p-3 border border-purple-100 leading-relaxed">
                                {visualizationData.description}
                              </p>
                            </motion.div>
                          )}
                        </AnimatePresence>
                      </div>
                    )}

                    {/* Info Badge */}
                    <div className="flex items-center gap-2 text-xs text-gray-400">
                      <Sparkles size={12} />
                      <span>Generated by Gemini 2.5 Flash • Click fullscreen for best view</span>
                    </div>
                  </div>
                ) : isMermaid ? (
                  /* ===== Mermaid Fallback ===== */
                  <MermaidFallback />
                ) : (
                  /* ===== Unknown format ===== */
                  <div className="bg-gray-50 rounded-lg p-4">
                    <pre className="text-sm text-gray-700 whitespace-pre-wrap font-mono">
                      {JSON.stringify(visualizationData, null, 2)}
                    </pre>
                  </div>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </>
  );
}
